apiVersion: apps/v1beta2
kind: ReplicaSet
metadata:
  name: hello-rs
  namespace: helloworld
  labels:
    app: hello-rs
    zone: prod
    vesrion: v1
spec:
  replicas: 3
  selector:
     matchLabels:
       app: hello-rs
  template:
    metadata:
      labels:
        app: hello-rs
    spec:
       containers:
         - name: hello-cntr-rs
           image: metamagicglobal/hello:v1.0
           imagePullPolicy: IfNotPresent
           ports:
            - containerPort: 80
