apiVersion: batch/v1
kind: Job
metadata:
  name: hellokubernetes
spec:
  template:
    spec:
      containers:
      - name: hellokubernetes
        image: metamagic/podshell
        command: ["echo", "Hello Kubernetes!!!"]
      restartPolicy: Never
