apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-tc2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"