apiVersion: v1
kind: Service
metadata:
  name: omega-svc-tc4
  labels:
    app: omega-svc-tc4
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: omega
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: websc-one
spec:
  selector:
    matchLabels:
      app: omega # has to match .spec.template.metadata.labels
  serviceName: "omega-svc"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: omega # has to match .spec.selector.matchLabels
    spec:
      volumes:
        - name: nfs-statefulset
          persistentVolumeClaim:
           # Local Storage Claim
           claimName: nfs-pv-claim    
      terminationGracePeriodSeconds: 10
      containers:
      - name: omega
        image: metamagic/oshell
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: nfs-statefulset
          mountPath: /home/data