apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-statefulset
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"