apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs
  labels:
    name: efs-aws
spec:
  storageClassName: aws-efs
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: fs-6efa3c24.efs.us-east-1.amazonaws.com
    path: /