kind: Service
apiVersion: v1
metadata:
  name: hello-service
  namespace: helloworld
spec:
  selector:
    app: hello
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443