apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: shoppingportal-istio
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP

