apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: ui-viewer
  namespace: shoppingportal
spec:
  rules:
  - services: ["k8uiworkshopservice.shoppingportal.svc.cluster.local"]
    methods: ["GET"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-ui-viewer
  namespace: shoppingportal
spec:
  subjects:
  - user: "*"
  roleRef:
    kind: ServiceRole
    name: "ui-viewer"