kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-volume
  namespace: sigma
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
