apiVersion: v1
kind: Pod
metadata:
  name: hello-pod-cip
  namespace: helloworld
  labels:
    app: hello-cip
    zone: prod
    version: v1
spec:
  containers:
  - name: hello-cntr
    image: metamagicglobal/hello:v1.0
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 80
