apiVersion: v1
kind: PersistentVolume
metadata:
  name: omega-volume-local
  labels:
    name: storage-local
spec:
  storageClassName: omega-sc-local
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/Users/arafkarsh/data/"
