apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-rwx-10gb-disk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  # Filesystem or Block (v1.13) Default = Filesystem
  volumeMode: Filesystem 
  nfs:
    server: nfs-server.default.svc.cluster.local
    path: "/"