kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs-rox-5gb-disk
spec:
  accessModes:
    - ReadOnlyMany
  # Filesystem or Block (v1.13) Default = Filesystem
  volumeMode: Filesystem 
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi 