apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRole
metadata:
  name: service-viewer
  namespace: shoppingportal
spec:
  rules:
  - services: ["*.shoppingportal.svc.cluster.local"]
    methods: ["GET", "POST"]
---
apiVersion: "rbac.istio.io/v1alpha1"
kind: ServiceRoleBinding
metadata:
  name: bind-service-viewer
  namespace: shoppingportal
spec:
  subjects:
  - properties:
      source.namespace: "shoppingportal"
  roleRef:
    kind: ServiceRole
    name: "service-viewer"