apiVersion: v1
kind: Pod
metadata:
  name: hellotwo-pod
  labels:
    app: hello
    zone: prod
    version: v2
spec:
  containers:
  - name: hellotwo-cntr
    image: metamagicglobal/hello:v1.1
    imagePullPolicy: IfNotPresent
    ports:
     - containerPort: 80
