apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: helloworld
  labels:
    app: nginx
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: helloworld-sa
      containers:
      - name: nginx
        image: nginx:1.13
        ports:
        - containerPort: 80