apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-helloworld
  namespace: helloworld
subjects:
- kind: ServiceAccount
  name: helloworld-sa
roleRef:
  kind: Role
  name: r-helloworld
  apiGroup: rbac.authorization.k8s.io