apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: omega-aws-deploy
  namespace: omega-aws
spec:
  replicas: 5
  selector:
    matchLabels:
      desire3d.io/name: omega-pod-aws
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        desire3d.io/name: omega-pod-aws
        desire3d.io/version: "1.0.0"
        desire3d.io/release: stable
        desire3d.io/tier: be
        desire3d.io/zone: prod
        desire3d.io/managed-by: m2
    spec:
      volumes:
        - name: omega-volume-aws
          persistentVolumeClaim:
           # Local Storage Claim
           claimName: omega-pvc-aws
      containers:
        - name: omega-ctr
          image: metamagic/oshell
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          resources:
             limits:
               cpu: "1000m"
          volumeMounts:
          # Mount omega-fs from persistentVolumeClaim
            - mountPath: "/home/data"
              name: omega-volume-aws
