apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
  namespace: policy-demo
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
